name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step to check out the code
      - name: Checkout
        uses: actions/checkout@v2

      # Step to install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      # Step for linting (optional)
      - name: Lint Code
        run: |
          pip install flake8  # or your preferred linter
          flake8 .  # Lint the entire repository

      # Step for unit testing (optional)
      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests  # Adjust according to your test structure
